services:
  acea_concert:
    build:
      context: .
    image: acea_concert:latest
    stdin_open: true
    tty: true 
    privileged: true
    command: ["/bin/bash", "-c", "bash /home/user/concert_ws/src/acea_concert/mount_files/patch_container.sh && exec bash"]
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # x11
      - ${XAUTHORITY}:${XAUTHORITY}:ro
      - ~/.ssh:/home/user/.ssh  # ssh
      - ~/Qt:/home/user/Qt  # qt
      - ../../acea_concert:/home/user/concert_ws/src/acea_concert:rw  # mount whole acea_concert folder
      # - ../mount_files/config_file.yaml:/home/user/patch/config_file.yaml:ro  # config file
      # - ../mount_files/concert_prismatic.py:/home/user/patch/concert_prismatic.py:ro  # prismatic script
      # - ../mount_files/patch_container.sh:/home/user/patch/patch_container.sh:ro
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - TERM=xterm-256color
      - NVIDIA_DRIVER_CAPABILITIES=all
 #   deploy:
 #     resources:
 #       reservations:
 #         devices:
 #           - driver: nvidia
 #             count: 1
 #             capabilities: [gpu]
