solver_options:
  regularization: 1e-4
  back_end: "qpoases"

stack:
  - ["base"]
  - ["ee_F"]
  - ["Postural"]

constraints:
  - joint_limits
  - velocity_limits

base:
  type: Cartesian
  distal_link: base_link
  base_link: world
  lambda: 1.0
  
ee_F:
  type: Cartesian
  distal_link: ee_F
  base_link: base_link
  lambda: 1.0

Postural:
  type: Postural
  lambda: 1.0

joint_limits:
  type: JointLimits

velocity_limits:
  type: VelocityLimits
